---
version: 2.1
orbs:
  docker: circleci/docker@2.2.0
workflows:
  test-app:
    jobs:
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          update-description: true
          context:
            - common
          filters:
            branches:
              ignore:
                - /pull\/.*/
            tags:
              only: /.*/
